import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F4F6F8" },
  content: { padding: 16 },

  sectionTitle: {
    fontSize: width * 0.045,
    fontWeight: "700",
    color: "#444",
    marginBottom: 12,
    marginTop: 8,
  },

  proveedorBtn: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  proveedorBtnText: { fontSize: 14, color: "#aaa" },
  proveedorSeleccionado: { fontSize: 14, color: "#333", fontWeight: "600" },

  itemRow: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  itemInfo: { flex: 1 },
  itemNombre: { fontSize: 14, fontWeight: "700", color: "#333" },
  itemSub: { fontSize: 12, color: "#888", marginTop: 2 },
  itemControls: { flexDirection: "row", alignItems: "center", gap: 10 },
  cantBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: "#f4a261",
    justifyContent: "center",
    alignItems: "center",
  },
  cantBtnText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 20,
  },
  cantText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
    minWidth: 24,
    textAlign: "center",
  },
  removeBtn: { padding: 4 },
  removeBtnText: { fontSize: 18, color: "#f44336" },

  addProductoBtn: {
    borderWidth: 1.5,
    borderColor: "#4CAF50",
    borderStyle: "dashed",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    marginBottom: 16,
  },
  addProductoBtnText: { color: "#4CAF50", fontWeight: "700", fontSize: 14 },

  totalCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  totalLabel: { fontSize: 14, color: "#888" },
  totalValue: { fontSize: 14, color: "#333", fontWeight: "600" },
  totalFinalLabel: { fontSize: 16, fontWeight: "700", color: "#333" },
  totalFinalValue: { fontSize: 18, fontWeight: "700", color: "#4CAF50" },

  emptyContainer: { alignItems: "center", paddingVertical: 30 },
  emptyIcon: { fontSize: 40, marginBottom: 8 },
  emptyText: { fontSize: 14, color: "#aaa" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: { fontSize: width * 0.048, fontWeight: "700", color: "#333" },
  closeButton: { fontSize: 22, color: "#aaa" },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F4F6F8",
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  searchIcon: { fontSize: 14, marginRight: 8, color: "#aaa" },
  searchInput: { flex: 1, paddingVertical: 10, fontSize: 14, color: "#333" },
  optionRow: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  optionNombre: { fontSize: 14, fontWeight: "700", color: "#333" },
  optionSub: { fontSize: 12, color: "#888", marginTop: 2 },

  errorText: { color: "red", fontSize: 12, marginBottom: 8 },
  formLabel: { fontSize: 13, color: "#666", marginBottom: 4, marginTop: 6 },
});
