import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F4F6F8" },
  content: { padding: 16 },

  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  searchIcon: { fontSize: 16, marginRight: 8, color: "#aaa" },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: width * 0.035,
    color: "#333",
  },

  filterContainer: { flexDirection: "row", gap: 8, marginBottom: 12 },
  filterChip: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    alignItems: "center",
  },
  filterChipEntrada: { backgroundColor: "#e8f5e9", borderColor: "#4CAF50" },
  filterChipSalida: { backgroundColor: "#fdecea", borderColor: "#f44336" },
  filterChipActive: { backgroundColor: "#2196F3", borderColor: "#2196F3" },
  filterChipText: { fontSize: 12, color: "#555", fontWeight: "600" },
  filterChipTextActive: { color: "#fff" },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: { fontSize: width * 0.045, fontWeight: "700", color: "#444" },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 8 },
  totalBadge: {
    backgroundColor: "#2196F3",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  totalText: { color: "#fff", fontSize: 12, fontWeight: "700" },
  addButton: {
    backgroundColor: "#f4a261",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  addButtonText: { color: "#fff", fontWeight: "700", fontSize: 13 },

  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  tipoBadge: {
    width: 52,
    height: 52,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  entrada: { backgroundColor: "#e8f5e9" },
  salida: { backgroundColor: "#fdecea" },
  tipoIcon: { fontSize: 20 },
  tipoText: { fontSize: 10, fontWeight: "700" },
  tipoTextEntrada: { color: "#4CAF50" },
  tipoTextSalida: { color: "#f44336" },
  info: { flex: 1 },
  descripcion: {
    fontSize: 14,
    fontWeight: "700",
    color: "#333",
    marginBottom: 2,
  },
  sub: { fontSize: 12, color: "#888", marginBottom: 4 },
  row: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
  badge: {
    fontSize: 11,
    color: "#555",
    backgroundColor: "#f0f0f0",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  monto: { fontSize: 15, fontWeight: "700", color: "#333" },

  emptyContainer: { alignItems: "center", paddingVertical: 40 },
  emptyIcon: { fontSize: 48, marginBottom: 10 },
  emptyText: { fontSize: 15, color: "#aaa" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: { fontSize: width * 0.05, fontWeight: "700", color: "#333" },
  closeButton: { fontSize: 22, color: "#aaa" },

  tipoSelector: { flexDirection: "row", gap: 10, marginBottom: 10 },
  tipoBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  tipoBtnEntrada: { backgroundColor: "#e8f5e9", borderColor: "#4CAF50" },
  tipoBtnSalida: { backgroundColor: "#fdecea", borderColor: "#f44336" },
  tipoBtnText: { fontWeight: "700", color: "#555" },
  tipoBtnTextEntrada: { color: "#4CAF50" },
  tipoBtnTextSalida: { color: "#f44336" },

  errorText: { color: "red", fontSize: 12, marginBottom: 6, marginTop: -6 },

  pagination: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    marginBottom: 20,
  },
  pageButton: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  pageButtonActive: { backgroundColor: "#2196F3", borderColor: "#2196F3" },
  pageButtonDisabled: { opacity: 0.4 },
  pageButtonText: { fontSize: 13, color: "#555", fontWeight: "600" },
  pageButtonTextActive: { color: "#fff" },
});
